---
name: Build
on:
  push:
    branches:
    - "**"
    - "!master"
    tags-ignore: "**"

env:
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GitHub_PAT }}

jobs:
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true # 'recursive' 'true' or 'false'
        token: ${{ secrets.GitHub_PAT }} # `GitHub_PAT` is a secret contains your PAT.
    - run: echo "${GITHUB_TOKEN}" | docker login -u stardust-c3po --password-stdin docker.pkg.github.com
    - run: docker run -i -u "$(id -u)" -v "$(pwd):/source" --rm -e CMAKE_OPTIONS="-DCMAKE_INSTALL_PREFIX=/usr -DEMBEDDED=ON" docker.pkg.github.com/ultimaker/print-cluster-jedi-scripts/print-cluster-jedi-scripts-cmake:latest
